[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/zekroTJA/discordgo"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/foxbot/gavalink"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "1.10.0"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "github.com/op/go-logging"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/zekroTJA/timedmap"

[[constraint]]
  branch = "master"
  name = "github.com/zekroTJA/ratelimit"
